const BASE_URL = "/api/v1";

const PASSWORD_MIN_LENGTH = 8;
const BULK_WRITE_BATCH_SIZE = 50;

const SHORT_TEXT_MAX_LENGTH = 500;
const LONG_TEXT_MAX_LENGTH = 1000;
const LONG_2X_TEXT_MAX_LENGTH = 2000;
const LONG_3X_TEXT_MAX_LENGTH = 3000;
const LONG_4X_TEXT_MAX_LENGTH = 4000;
const LONG_5X_TEXT_MAX_LENGTH = 5000;

const PAGINATION = {
  PAGE: 1,
  SIZE: 10,
};

const LOG_LEVELS = {
  error: 0,
  warn: 1,
  info: 2,
  http: 3,
  debug: 4,
};

module.exports = {
  BASE_URL,
  PASSWORD_MIN_LENGTH,
  BULK_WRITE_BATCH_SIZE,
  SHORT_TEXT_MAX_LENGTH,
  LONG_TEXT_MAX_LENGTH,
  LONG_2X_TEXT_MAX_LENGTH,
  LONG_3X_TEXT_MAX_LENGTH,
  LONG_4X_TEXT_MAX_LENGTH,
  LONG_5X_TEXT_MAX_LENGTH,
  PAGINATION,
  LOG_LEVELS,
};
